In [13]:
import numpy as np
import pandas as pd

arr = np.load(r"C:\Users\VCI RG\OneDrive\Desktop\Machine Learning\Digital Twin and AI chemical engineering\Hybrid Modelling\cstr_rawdata.npy")
print(arr.shape, arr.dtype)

df = pd.DataFrame(arr)
df.head()



# If it's flattened sequences + trailing metadata:
#sequences = arr[:, :1400].reshape(-1, 200, 7)   # matches your LSTM model's input shape
#extra_cols = arr[:, 1400:]                       # last 4 columns
#print(extra_cols[:10])

(2860, 1404) float64

,0,1,2,3,4,5,6,7,8,9,...,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403
0,0.999719,0.999854,1.000517,0.999764,0.999982,1.000978,1.000314,0.999953,0.999051,1.000165,...,10.097724,10.042699,9.963228,10.084302,10.548740,10.032248,0.0,0.0,0.0,1.0
1,1.002411,1.000820,1.001000,0.999042,0.999200,1.001231,1.001470,1.001782,0.999543,0.999201,...,9.731097,10.080027,9.896257,9.088898,9.798987,10.418807,0.0,0.0,0.0,1.0
2,0.999197,0.998922,1.000095,0.999389,0.999128,0.999978,0.999889,1.001926,1.000072,0.999326,...,10.041097,9.745254,10.877219,9.592610,10.046595,10.262627,0.0,0.0,0.0,1.0
3,1.000770,1.000499,0.999830,1.000854,1.001071,1.001708,0.999969,0.998799,1.000446,0.999382,...,10.570380,9.610376,10.546058,10.679968,10.282365,10.035451,0.0,0.0,0.0,1.0
4,1.001674,1.000058,0.999202,0.998686,0.999539,0.999194,1.000795,1.000007,0.999421,1.000157,...,9.787158,9.954904,10.416254,9.866833,10.053383,10.025643,0.0,0.0,0.0,1.0

In [14]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403
2855,1.000140,0.999521,0.999704,0.999806,0.998136,0.999943,0.997705,1.001024,1.000779,1.000523,...,10.357571,9.388529,10.603407,10.486673,10.366741,10.151244,12.0,6.0,0.15,2.0
2856,1.000362,0.999980,1.000894,0.999308,1.001345,0.999591,1.000885,1.000781,0.999566,1.000374,...,109.785223,184.494604,18.818820,14.126765,199.905112,69.061973,12.0,6.0,0.15,2.0
2857,0.999077,1.001366,1.000017,0.999225,1.000212,0.999729,0.999154,1.001117,0.999413,1.000502,...,9.471558,28.000428,176.543604,28.936357,8.944380,176.151994,12.0,6.0,0.15,2.0
2858,1.001098,1.000214,1.000179,0.999343,1.002278,1.000047,0.998181,1.000011,0.998720,1.002250,...,10.078710,53.954812,136.188957,10.326120,9.743213,142.911790,12.0,6.0,0.15,2.0
2859,1.000892,1.000215,1.000339,1.001189,1.000395,1.001613,0.999377,1.000374,0.999420,0.999515,...,130.864934,9.833270,10.218620,177.376757,45.741346,9.289705,12.0,6.0,0.15,2.0